### ISSUE TITLE
SUBDOMAIN_DEFAULT setting

### ISSUE THREAD

**Issue by digitex** [playfire/django-dynamic-subdomains#1]
It seems that the middleware requires SUBDOMAIN_DEFAULT setting. What should be this setting?

**Comment by lamby** [comment]
Each entry in the SUBDOMAINS setting should have a "name" keyword argument - SUBDOMAIN_DEFAULT should refer to one of those.

I admit this is a bit unwieldy and will look into improving it shortly.

**Comment by digitex** [comment]
Awesome! Works now.

**Comment by lamby** [comment]
Great. Be advised that the settings may change in the near future - I will update the documentation then.
