### ISSUE TITLE
Domain without www?

### ISSUE THREAD

**Issue by digitex** [playfire/django-dynamic-subdomains#2]
Hi there,

How do we account for domain without the www, i.e. http://abc.com. Tried ^$ but can't work.

**Comment by lamby** [comment]
Just to be sure we aren't confusing each other, can you paste your SUBDOMAINS setting with an outline of what you want to do? Feel free to anonymise.

I'm pretty sure you just need to set the regex to r'^abc.com$' though.

-- lamby

**Comment by digitex** [comment]
@lamby

Referring to the example in middleware.py

```
SUBDOMAINS = patterns(
    subdomain('www', ROOT_URLCONF, name='static'),
    subdomain('(?P<username>\w+)', 'path.to.custom_urls',
            callback='path.to.custom_fn', name='with-callback'),
)
```

If I point my browser to www.abc.com it matchs against 'www'. When I discard the www, that is just abc.com it matches against the 2nd one. I would like it to point to ROOT_URLCONF instead of path.to.custom_urls.

So I tried subdomain('(^$)', ROOT_URLCONF, name='static-non-www') but can't work. Might be the regex problem.

**Comment by lamby** [comment]
Since writing that documentation, I now recommend you use fully qualified domain names instead of just the subdomains part. This is a bit clearer, but the main advantage is the ability to "reverse" subdomains so you don't have to manually construct urls.

So, try changing everything to:

```
SUBDOMAINS = patterns(
    subdomain(r'^(www\.)?abc\.com$', ROOT_URLCONF, name='static'),
    subdomain(r'^(?P<username>\w+)\.abc\.com$', 'path.to.custom_urls',
            callback='path.to.custom_fn', name='with-callback'),
)
```

**Comment by digitex** [comment]
@lamby

Thanks!
